# Activa la Edge Function SOLO para proxiar el HLS
[[edge_functions]]
path = "/americabletv/*"
function = "hls-proxy"

# (Opcional) Fuerza HTTPS en tu dominio
[[redirects]]
from = "http://*americabletv.com/*"
to = "https://americabletv.com/:splat"
status = 301
force = true
